"""Add name to boards

Revision ID: 20200130192235
Revises: 20200125211816
Create Date: 2020-01-30 19:22:36.486032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20200130192235'
down_revision = '20200125211816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'name')
    # ### end Alembic commands ###
